###############################################
# V-257788 | RHEL-09-212015
# Rule Title: RHEL 9 must disable the ability of systemd to spawn an interactive boot process.
# Fix Text: Remove the "systemd.confirm_spawn" argument from GRUB 2 configuration.
###############################################
- name: Disable interactive boot process (remove systemd.confirm_spawn) (V-257788)
  command: grubby --update-kernel=ALL --remove-args="systemd.confirm_spawn"
  become: yes
  tags:
    - V-257788
    - RHEL-09-212015
    - interactive_boot

###############################################
# V-257796 | RHEL-09-212055
# Rule Title: RHEL 9 must enable auditing of processes that start prior to the audit daemon.
# Fix Text: Enable auditing via GRUB kernel arguments.
###############################################
- name: Enable auditing of early processes via GRUB (V-257796)
  command: grubby --update-kernel=ALL --args="audit=1"
  become: yes
  tags:
    - V-257796
    - RHEL-09-212055
    - audit_pre_daemon